### ISSUE TITLE
Complete no movement

### ISSUE THREAD

**Issue by Tomoli75** [DragonetMC/DragonProxy#165] opened 2017-12-26 18:55 UTC
When punched, the PE client emulates movement. The PC client does not.
Breaking blocks, the PE client shows it works. The PC client does not.
When even moving or rotating, the PE client shows it works, the PC client doesn't.

To reproduce, just simply download both the latest dragon proxy and the spigot from getbukkit.org, and run both the dragon (first) and the server (second).
Connect using an iOS device and just try moving and punching the client on a java edition account.

Please help!

**Comment by Tomoli75** [comment] 2017-12-26 19:05
& kicking doesn't work either

**Comment by Tomoli75** [comment] 2017-12-26 19:07
Teleportation using essentialsX works, yet movement after that doesn't, as usual.

**Comment by DefinitlyEvil** [comment] 2017-12-27 05:15
this software is under development, those are not implmented yet!

**Comment by Tomoli75** [comment] 2017-12-27 07:36
So, moving is not implimented? How does that even...

**Comment by Tomoli75** [comment] 2017-12-27 07:36
@DefinitlyEvil

**Comment by HoverEpic** [comment] 2017-12-27 10:13
I cant test with IOS, but moving works on all other plateforms.
All the other things you have listed are non functional : 
- attack
- interact entity
- breaking blocks

**Comment by HoverEpic** [comment] 2017-12-27 10:37
I'm actualy testing and you'r right, pc client don't handle movments, i'll work on it today.

**Comment by DefinitlyEvil** [comment] 2017-12-27 11:03
I fixed movement in 0.3.3.1, your movement didn't work maybe caused by slabs/staircases/half-blocks.

**Comment by HoverEpic** [comment] 2017-12-27 11:13
ok, i'm testing all cases to validate it's working.

**Comment by DefinitlyEvil** [comment] 2017-12-27 12:15
thx

**Comment by DefinitlyEvil** [comment] 2017-12-28 06:22
closing this for now, if error still occurs, re-open it!

**Closed as completed by DefinitlyEvil** 2017-12-28 06:22 UTC
Labels: Bug, Priority: Critical
