### ISSUE TITLE
Fail when compiling.

### ISSUE THREAD

**Issue by qwertyazerty** [DragonetMC/DragonProxy#22] opened 2016-09-02 20:14 UTC
I tried to compile by following your tutoriel. This is not the first time I do that.
I did it on Ubuntu and Windows and get the same issue.
The logs ( Windows, same on Linux ).
[logs.txt](https://github.com/DragonetMC/DragonProxy/files/452838/logs.txt)

**Comment by iDerp** [comment] 2016-09-02 20:39
The latest build, and quite a few before were failing. https://drone.io/github.com/DragonetMC/DragonProxy/latest

**Comment by TheDiamondYT1** [comment] 2016-09-03 09:38
Yeah blame me i need someone to fix the maven build, or revert to before maven modules

@DefinitlyEvil @mastercoms @TekkitCommando @MrPowerGamerBR @MrGenga @TheMCPEGamer

**Comment by DaMatrix** [comment] 2016-09-03 10:57
The problem is that protocol depends on proxy, and proxy depends on protocol.  Neither of them can be built.  Would it be a problem if I merged the two in a PR?

**Comment by TheDiamondYT1** [comment] 2016-09-03 11:00
Okay

**Closed as completed** 2016-09-03 11:36 UTC
