### ISSUE TITLE
Maven is broken for optional plugin jars

### ISSUE THREAD

**Issue by MatrixTunnel** [DragonetMC/DragonProxy#256] opened 2018-02-25 04:18 UTC
When compiling the optional plugin jars for bungee, spigot, or universal, the `dragonproxy-protocol` dependency isn't properly shaded into the final jar resulting in errors when players join and other general problems.

Here is the stack trace showing the ClassNotFoundException proving the jar dependencies weren't shaded properly: https://hastebin.com/jikevecivu.vbs The commons lib is in the protocol lib which should be in the final jar but isn't

**Comment by lukeeey** [comment] 2018-02-25 10:35
If you build the root project it should also build the plugin projects. Well, that's what it did with me

**Comment by HoverEpic** [comment] 2018-02-25 12:23
the shading is wip, it doesn't include important files, and im focusing on proxy.

**Comment by HoverEpic** [comment] 2018-03-02 11:34
@sgdc3 can you take a look at this?

**Comment by sgdc3** [comment] 2018-03-02 12:42
@HoverEpic the PR should address that, i'll probably remove the universal jar for the moment (which is not working as intended due to some weird maven behaviour) so the PR can be merged.

**Comment by HoverEpic** [comment] 2018-03-09 09:43
Should be ok

**Closed as completed** 2018-03-09 09:43 UTC
