### ISSUE TITLE
color on UNIX hosts

### ISSUE THREAD

**Issue by Erkam246** [DragonetMC/DragonProxy#192] opened 2018-01-04 13:57 UTC
```
[14:54:25] [INFO] §a----[ All commands for DragonProxy ]----
[14:54:25] [INFO] §2help: §fDisplays commands for DragonProxy
[14:54:25] [INFO] §2kill: §fForcefully kill the proxy
[14:54:25] [INFO] §2stop: §fStop the proxy
[14:54:25] [INFO] §2test: §f
```

**Comment by x9nico** [comment] 2018-01-04 21:26
It is do the same on Windows

**Comment by ApocalypsjeNL** [comment] 2018-01-04 21:29
It's not a bug, as shown in this code the colors are actually implemented https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/utilities/Logger.java#L57-L64

**Comment by lukeeey** [comment] 2018-01-04 22:44
@HoverEpic We need to have a method to remove the colour codes if the colorful variable is not true in MCColor

**Comment by ApocalypsjeNL** [comment] 2018-01-04 22:52
Should be an easy fix, and maybe als add an option to the config? Because the Boolean is defined at the top of the file and never updated anywhere

**Comment by lukeeey** [comment] 2018-01-04 22:58
I put the boolean there because i forgot to add an option to disable ansi

**Comment by lukeeey** [comment] 2018-01-04 23:01
I could add a startup option to disable ansi

**Comment by HoverEpic** [comment] 2018-01-04 23:27
Or we need to implements ansii colors codes.

**Comment by ApocalypsjeNL** [comment] 2018-01-04 23:30
They are, as mentioned above https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/utilities/Logger.java#L57-L64

**Comment by lukeeey** [comment] 2018-01-04 23:34
Look at MCColor.java @HoverEpic

**Comment by DefinitlyEvil** [comment] 2018-01-05 04:52
I think it uses ANSI color codes.

**Comment by ApocalypsjeNL** [comment] 2018-01-05 07:26
It does indeed @DefinitlyEvil, only problem is that colorful (https://github.com/DragonetMC/DragonProxy/blob/master/src/main/java/org/dragonet/proxy/utilities/Logger.java#L22) always false is because it's never updated somewhere, and so is the ansi color function never been called

**Comment by DefinitlyEvil** [comment] 2018-01-05 07:55
@ApocalypsjeNL ahh I see

**Comment by HoverEpic** [comment] 2018-01-05 09:44
No it does not implements ansii colors, it's minecraft colors, two different things (we need this https://github.com/fusesource/jansi)

**Comment by HoverEpic** [comment] 2018-01-05 09:50
I just woke up I missread >< (didtn't see the toANSI()....) let' fix this =)

**Comment by HoverEpic** [comment] 2018-01-05 10:15
It's fixed in the next release (https://github.com/DragonetMC/DragonProxy/commit/e4a1806e38befc3a6e61e26a0935841e6f91ec3c)

**Closed as completed by HoverEpic** 2018-01-05 10:15 UTC
Labels: Bug
