### ISSUE TITLE
Spaces in bedrock names.

### ISSUE THREAD

**Issue by Navoei** [DragonetMC/DragonProxy#532] opened 2020-04-26 00:42 UTC
This is not necessarily an issue, but more of a request. 
It might be an issue on some server though. 
Bedrock clients can have spaces in their name. This can cause severe issues in Java servers where spaces signify the start of a new argument in a command. 
For example, the command '/ban Navoei MC' would not work because the username 'Navoei MC' has a space in it.

**Comment by Chew** [comment] 2020-04-26 01:06
Duplicate of #255

**Comment by Chew** [comment] 2020-04-26 01:06
Although I don't know why that one was closed

**Comment by lukeeey** [comment] 2020-04-26 01:11
It was from 2018

**Comment by james090500** [comment] 2020-04-26 01:49
Does java even allow players with spaces to connect?

**Comment by Chew** [comment] 2020-04-26 01:50
can check

**Comment by Chew** [comment] 2020-04-26 01:52
Yes actually, on offline servers

**Comment by Chew** [comment] 2020-04-26 01:54
Problem is they're invincible, you can't ban or do anything with them

**Comment by james090500** [comment] 2020-04-26 02:01
That sounds like a minecraft bug then. Players should be stopped having invalid usernames on java side

**Comment by Chew** [comment] 2020-04-26 02:13
I made an issue for it https://bugs.mojang.com/browse/MC-180850 but I doubt they'll fix it

**Comment by KanekiOnMC** [comment] 2020-04-26 07:31
No don't Worry they are not really invicible, you can use that ""
example: /ban "Good Nickname", and not /ban Good Nickname
That option is already in Minecraft Bedrock Edition and Minecraft Java Edition

**Comment by lukeeey** [comment] 2020-04-26 10:09
I don’t get how people don’t know that

**Comment by james090500** [comment] 2020-04-27 23:18
Due to the fact this should be handled on Java's side to stop connection with spaces I am closing this issue.

**Closed as completed by james090500** 2020-04-27 23:18 UTC
