### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by patricknasci** [DragonetMC/DragonProxy#242] opened 2018-02-16 11:13 UTC
![captura de tela_2018-02-16_09-12-16](https://user-images.githubusercontent.com/11508790/36305192-ad6bd9da-12f9-11e8-9258-e533b0654d8b.png)

**Comment by lukeeey** [comment] 2018-02-16 11:16
@DragonetMC/developers i'm not sure if this is an error or just general debug, but the code creating that message can be found here: https://github.com/DragonetMC/DragonProxy/blob/e035affac6ef5ffd81c5efaaf173740e8a16b88f/proxy/src/main/java/org/dragonet/proxy/network/translator/pc/PCClosedWindowPacketTranslator.java#L24

**Comment by patricknasci** [comment] 2018-02-16 11:27
this message spam happens when a player enters and tries to climb the stairs, and when he puts blocks on the floor a message appears: TYPE_USE_ITEM

**Comment by lukeeey** [comment] 2018-02-16 11:29
That code can be found here: https://github.com/DragonetMC/DragonProxy/blob/41016040891e2498993e8411eb842d609c28f8fe/proxy/src/main/java/org/dragonet/proxy/network/translator/pe/PEInventoryTransactionPacketTranslator.java#L141

**Comment by patricknasci** [comment] 2018-02-16 11:29
java.lang.NullPointerException
        at org.dragonet.proxy.utilities.BinaryStream.putString(BinaryStream.java:374)
        at org.dragonet.proxy.protocol.packets.AddPlayerPacket.encodePayload(AddPlayerPacket.java:46)
        at org.dragonet.proxy.protocol.PEPacket.encode(PEPacket.java:28)
        at org.dragonet.proxy.network.UpstreamSession.sendPacket(UpstreamSession.java:177)
        at org.dragonet.proxy.network.UpstreamSession.sendPacket(UpstreamSession.java:170)
        at org.dragonet.proxy.network.cache.CachedEntity.spawn(CachedEntity.java:150)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:12)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:8)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:149)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
        at java.lang.Thread.run(Thread.java:748)
[09:11:45] [DEBUG] PING /192.168.15.11:44973
[09:11:45] [DEBUG] CLIENT DISCONNECT

**Comment by patricknasci** [comment] 2018-02-16 11:30
```
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
Window 0 closed from server !
TYPE_USE_ITEM
TYPE_USE_ITEM
TYPE_USE_ITEM
java.lang.NullPointerException
        at org.dragonet.proxy.utilities.BinaryStream.putString(BinaryStream.java:374)
        at org.dragonet.proxy.protocol.packets.AddPlayerPacket.encodePayload(AddPlayerPacket.java:46)
        at org.dragonet.proxy.protocol.PEPacket.encode(PEPacket.java:28)
        at org.dragonet.proxy.network.UpstreamSession.sendPacket(UpstreamSession.java:177)
        at org.dragonet.proxy.network.UpstreamSession.sendPacket(UpstreamSession.java:170)
        at org.dragonet.proxy.network.cache.CachedEntity.spawn(CachedEntity.java:150)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:12)
        at org.dragonet.proxy.network.translator.pc.PCSpawnPlayerPacketTranslator.translate(PCSpawnPlayerPacketTranslator.java:8)
        at org.dragonet.proxy.network.PacketTranslatorRegister.translateToPE(PacketTranslatorRegister.java:149)
        at org.dragonet.proxy.network.PCDownstreamSession$1.packetReceived(PCDownstreamSession.java:85)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
        at java.lang.Thread.run(Thread.java:748)
[09:11:45] [DEBUG] PING /192.168.15.11:44973
[09:11:45] [DEBUG] CLIENT DISCONNECT
```

**Comment by HoverEpic** [comment] 2018-02-17 13:13
`Window 0 closed from server !` message and the error are not linked.
The spam message come probably from a plugin on the server, and means close the player inventory if it's open.
The error is the same as #241 (no players), so we'll talke about this in the correct issue.
I'm closing this issue as the spam message is not a bug (i guess).

**Closed as completed by HoverEpic** 2018-02-17 13:14 UTC
